Add verification step to AAS tutorial
eclipse-basyx/basyx-python-framework pull request #8
Opened 2024-10-15 10:36 UTC by JAB1305

2024-10-16 14:56 UTC, s-heppner requested changes

2024-10-16 14:56 UTC, s-heppner commented on sdk/basyx/tutorial/tutorial_create_simple_aas.py
> +# We can use aas_core3.verification.verify(). This method returns an Iterator that we can collect into a list and
Can you expand here on what's inside the Iterator? Probably a list of problems that would occur?

2024-10-18 20:11 UTC, JAB1305 commented on sdk/basyx/tutorial/tutorial_create_simple_aas.py
> +# We can use aas_core3.verification.verify(). This method returns an Iterator that we can collect into a list and
Yes, exactly that. Maybe update the desription to something like this?

```
# We can use aas_core3.verification.verify(). This method returns an Iterator that we can collect into a list and
# for demonstration reasons assert it to be empty. Each item in this iterator represents a violation of the AAS
# meta-model rules or constraints (e.g. Missing required fields, Invalid types of fields, ...).
```

2024-10-18 20:15 UTC, JAB1305 commented on sdk/basyx/tutorial/tutorial_create_simple_aas.py
> +# We can use aas_core3.verification.verify(). This method returns an Iterator that we can collect into a list and
And do we maybe want to add this link to the official documentation?
https://aas-core30-python.readthedocs.io/en/latest/getting_started/verify.html

2024-10-24 08:26 UTC, s-heppner commented on sdk/basyx/tutorial/tutorial_create_simple_aas.py
> +# We can use aas_core3.verification.verify(). This method returns an Iterator that we can collect into a list and
Yes, I like your text, and you can add: 

`For more information refer to the official aas-core documentation`. 

I don't think we should add a link to aas-core v3.0, considering the tutorial should stay valid even with newer versions of aas-core and then we will most definitely forget to update this link.

2024-10-25 06:36 UTC, s-heppner approved these changes

2024-10-25 06:36 UTC, merged